name: Auto Delete Merged Branches

on:
  push:
    branches:
      - main

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete merged branch
        run: |
          merged_branch=$(git rev-parse --abbrev-ref HEAD)
          git push origin --delete $merged_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
